
import React from 'react';
import { UserRole, User, EducationContent, ANCVisit } from './types';
import { LayoutDashboard, Users, UserPlus, BookOpen, MapPin, QrCode, Phone, ShieldCheck, Map as MapIcon, MessageSquare } from 'lucide-react';

export const PUSKESMAS_INFO = {
  name: "Puskesmas Pasar Minggu",
  address: "Jl. Kebagusan Raya No.4, RT.4/RW.4 12520 Jakarta Jakarta",
  phone: "+6289521868087",
  email: "kontak@puskesmas-pasarminggu.go.id",
  lat: -6.2996,
  lng: 106.8315
};

export const WILAYAH_DATA = {
  "Pasar Minggu": [
    "Pejaten Barat",
    "Pejaten Timur",
    "Pasar Minggu",
    "Kebagusan",
    "Jati Padang",
    "Ragunan",
    "Cilandak Timur"
  ]
};

export const NAVIGATION = [
  { name: 'Dashboard', icon: <LayoutDashboard size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES, UserRole.USER], path: 'dashboard' },
  { name: 'Data Pasien', icon: <Users size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES], path: 'patients' },
  { name: 'Monitoring Resiko', icon: <MapPin size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES], path: 'monitoring' },
  { name: 'Pemetaan Lokasi', icon: <MapIcon size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES], path: 'map' },
  { name: 'Pesan Siaran (WA)', icon: <MessageSquare size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES], path: 'broadcast' },
  { name: 'Pendaftaran ANC', icon: <UserPlus size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES], path: 'register' },
  { name: 'Manajemen Akses', icon: <ShieldCheck size={20} />, roles: [UserRole.ADMIN], path: 'management' },
  { name: 'Kartu ANC Pintar', icon: <QrCode size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES, UserRole.USER], path: 'smart-card' },
  { name: 'Edukasi Ibu', icon: <BookOpen size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES, UserRole.USER], path: 'education' },
  { name: 'Kontak Kami', icon: <Phone size={20} />, roles: [UserRole.ADMIN, UserRole.NAKES, UserRole.USER], path: 'contact' },
];

export const MOCK_USERS: User[] = [
  {
    id: 'admin',
    username: 'admin',
    password: 'admin123',
    name: 'Drg Ma`Mun (Admin)',
    dob: '1980-01-01',
    address: 'Kantor Puskesmas Pasar Minggu',
    kecamatan: 'Pasar Minggu',
    kelurahan: 'Pasar Minggu',
    hpht: '',
    pregnancyMonth: 0,
    pregnancyNumber: 0,
    parityP: 0,
    parityA: 0,
    medicalHistory: 'SYSTEM_ADMIN',
    role: UserRole.ADMIN,
    phone: '0812000000',
    isActive: true,
    selectedRiskFactors: [],
    totalRiskScore: 0
  },
  {
    id: 'bidan',
    username: 'bidan',
    password: 'bidan123',
    name: 'Bidan Siti, S.Tr.Keb',
    dob: '1985-03-10',
    address: 'Puskesmas Pasar Minggu',
    kecamatan: 'Pasar Minggu',
    kelurahan: 'Pasar Minggu',
    hpht: '',
    pregnancyMonth: 0,
    pregnancyNumber: 0,
    parityP: 0,
    parityA: 0,
    medicalHistory: 'SYSTEM_NAKES',
    role: UserRole.NAKES,
    phone: '0813000000',
    isActive: true,
    selectedRiskFactors: [],
    totalRiskScore: 0
  },
  {
    id: 'ANC-2025-1001',
    username: 'siti',
    password: '123',
    name: 'Ny. Siti Aminah',
    dob: '1998-05-12',
    address: 'Jl. Pejaten Raya No. 45',
    kecamatan: 'Pasar Minggu',
    kelurahan: 'Pejaten Barat',
    lat: -6.2850,
    lng: 106.8250,
    hpht: '2025-10-15',
    pregnancyMonth: 4,
    pregnancyNumber: 1,
    parityP: 0,
    parityA: 0,
    medicalHistory: 'Tidak ada riwayat penyakit',
    role: UserRole.USER,
    phone: '081299887711',
    isActive: true,
    selectedRiskFactors: [],
    totalRiskScore: 0
  },
  {
    id: 'ANC-2025-1002',
    username: 'linda',
    password: '123',
    name: 'Ny. Linda Kusuma',
    dob: '1988-10-20',
    address: 'Kavling Polri Blok D, Ragunan',
    kecamatan: 'Pasar Minggu',
    kelurahan: 'Ragunan',
    lat: -6.3120,
    lng: 106.8210,
    hpht: '2025-10-05',
    pregnancyMonth: 4,
    pregnancyNumber: 4,
    parityP: 3,
    parityA: 0,
    medicalHistory: 'Riwayat persalinan lama',
    role: UserRole.USER,
    phone: '081299887722',
    isActive: true,
    selectedRiskFactors: ['PARITY_HIGH'],
    totalRiskScore: 4
  },
  {
    id: 'ANC-2025-1003',
    username: 'dewi',
    password: '123',
    name: 'Ny. Dewi Rahayu',
    dob: '1990-02-14',
    address: 'Jl. Kebagusan Dalam IV',
    kecamatan: 'Pasar Minggu',
    kelurahan: 'Kebagusan',
    lat: -6.3050,
    lng: 106.8350,
    hpht: '2025-11-10',
    pregnancyMonth: 3,
    pregnancyNumber: 2,
    parityP: 1,
    parityA: 0,
    medicalHistory: 'Diabetes Melitus Tipe 2',
    role: UserRole.USER,
    phone: '081299887733',
    isActive: true,
    selectedRiskFactors: ['DIABETES'],
    totalRiskScore: 12
  },
  {
    id: 'ANC-2025-1004',
    username: 'fitri',
    password: '123',
    name: 'Ny. Fitri Handayani',
    dob: '1995-07-30',
    address: 'Gg. Seratus, Jati Padang',
    kecamatan: 'Pasar Minggu',
    kelurahan: 'Jati Padang',
    lat: -6.2920,
    lng: 106.8380,
    hpht: '2025-11-20',
    pregnancyMonth: 3,
    pregnancyNumber: 2,
    parityP: 1,
    parityA: 0,
    medicalHistory: 'Pernah keguguran sebelumnya',
    role: UserRole.USER,
    phone: '081299887744',
    isActive: true,
    selectedRiskFactors: ['SHORT_PREG'],
    totalRiskScore: 4
  },
  {
    id: 'ANC-2025-1005',
    username: 'andini',
    password: '123',
    name: 'Ny. Andini Putri',
    dob: '1999-01-25',
    address: 'Jl. Ampera Raya No. 12',
    kecamatan: 'Pasar Minggu',
    kelurahan: 'Cilandak Timur',
    lat: -6.2980,
    lng: 106.8150,
    hpht: '2025-11-25',
    pregnancyMonth: 3,
    pregnancyNumber: 1,
    parityP: 0,
    parityA: 0,
    medicalHistory: 'Sehat',
    role: UserRole.USER,
    phone: '081299887755',
    isActive: true,
    selectedRiskFactors: [],
    totalRiskScore: 0
  },
  // PASIEN MANGKIR 1 (MERAH)
  {
    id: 'ANC-2025-1006',
    username: 'rahma',
    password: '123',
    name: 'Ny. Rahmawati',
    dob: '1992-04-18',
    address: 'Jl. Jati Padang Baru No. 8',
    kecamatan: 'Pasar Minggu',
    kelurahan: 'Jati Padang',
    lat: -6.2910,
    lng: 106.8340,
    hpht: '2025-10-10',
    pregnancyMonth: 4,
    pregnancyNumber: 3,
    parityP: 2,
    parityA: 0,
    medicalHistory: 'Riwayat Sesar',
    role: UserRole.USER,
    phone: '081299887766',
    isActive: true,
    selectedRiskFactors: ['HISTORY_SC', 'HYPERTENSION'],
    totalRiskScore: 16
  },
  // PASIEN MANGKIR 2 (KUNING)
  {
    id: 'ANC-2025-1007',
    username: 'sari',
    password: '123',
    name: 'Ny. Sari Indah',
    dob: '1987-12-05',
    address: 'Pejaten Timur Gg. Damai',
    kecamatan: 'Pasar Minggu',
    kelurahan: 'Pejaten Timur',
    lat: -6.2890,
    lng: 106.8450,
    hpht: '2025-11-05',
    pregnancyMonth: 3,
    pregnancyNumber: 4,
    parityP: 3,
    parityA: 0,
    medicalHistory: 'Anemia sedang',
    role: UserRole.USER,
    phone: '081299887777',
    isActive: true,
    selectedRiskFactors: ['AGE_EXTREME', 'ANEMIA'],
    totalRiskScore: 8
  }
];

export const MOCK_ANC_VISITS: ANCVisit[] = [
  {
    id: 'v-siti-1',
    patientId: 'ANC-2025-1001',
    visitDate: '2026-02-05',
    scheduledDate: '2026-02-05',
    nextVisitDate: '2026-03-05',
    weight: 55.0,
    bloodPressure: '110/70',
    tfu: 14,
    djj: 140,
    hb: 12.5,
    complaints: 'Mual berkurang',
    dangerSigns: [],
    edema: false,
    fetalMovement: 'Normal',
    followUp: 'ANC_RUTIN',
    nakesNotes: 'Kondisi ibu janin baik.',
    nakesId: 'bidan',
    status: 'COMPLETED'
  },
  {
    id: 'v-linda-1',
    patientId: 'ANC-2025-1002',
    visitDate: '2026-01-05',
    scheduledDate: '2026-01-05',
    nextVisitDate: '2026-02-05',
    weight: 62.0,
    bloodPressure: '120/80',
    tfu: 15,
    djj: 142,
    hb: 11.2,
    complaints: 'Nyeri punggung',
    dangerSigns: [],
    edema: false,
    fetalMovement: 'Normal',
    followUp: 'ANC_RUTIN',
    nakesNotes: 'Edukasi istirahat.',
    nakesId: 'bidan',
    status: 'COMPLETED'
  },
  {
    id: 'v-dewi-1',
    patientId: 'ANC-2025-1003',
    visitDate: '2026-02-20',
    scheduledDate: '2026-02-20',
    nextVisitDate: '2026-03-05',
    weight: 68.5,
    bloodPressure: '135/85',
    tfu: 18,
    djj: 148,
    hb: 10.8,
    complaints: 'Cepat lelah',
    dangerSigns: [],
    edema: true,
    fetalMovement: 'Normal',
    followUp: 'KONSUL_DOKTER',
    nakesNotes: 'Rujuk konsultasi SpOG terkait GDM.',
    nakesId: 'bidan',
    status: 'COMPLETED'
  },
  {
    id: 'v-fitri-1',
    patientId: 'ANC-2025-1004',
    visitDate: '2026-01-10',
    scheduledDate: '2026-01-10',
    nextVisitDate: '2026-01-24',
    weight: 58.0,
    bloodPressure: '165/105',
    tfu: 12,
    djj: 110,
    hb: 9.5,
    complaints: 'Pusing hebat, pandangan kabur',
    dangerSigns: ['Pusing Hebat'],
    edema: true,
    fetalMovement: 'Kurang Aktif',
    followUp: 'RUJUK_RS',
    nakesNotes: 'Gawat Darurat! Pre-eklampsia berat. Pasien mangkir kontrol ulang.',
    nakesId: 'bidan',
    status: 'COMPLETED'
  },
  {
    id: 'v-andini-1',
    patientId: 'ANC-2025-1005',
    visitDate: '2026-02-15',
    scheduledDate: '2026-02-15',
    nextVisitDate: '2026-03-15',
    weight: 50.5,
    bloodPressure: '110/70',
    tfu: 10,
    djj: 145,
    hb: 13.0,
    complaints: 'Tidak ada',
    dangerSigns: [],
    edema: false,
    fetalMovement: 'Normal',
    followUp: 'ANC_RUTIN',
    nakesNotes: 'Sehat.',
    nakesId: 'bidan',
    status: 'COMPLETED'
  },
  // KUNJUNGAN PASIEN MANGKIR 1 (RAHMA - MANGKIR SEJAK JANUARI)
  {
    id: 'v-rahma-1',
    patientId: 'ANC-2025-1006',
    visitDate: '2025-12-15',
    scheduledDate: '2025-12-15',
    nextVisitDate: '2025-01-15', // SUDAH LEWAT JAUH
    weight: 65.0,
    bloodPressure: '140/90',
    tfu: 16,
    djj: 144,
    hb: 11.0,
    complaints: 'Pusing ringan',
    dangerSigns: [],
    edema: false,
    fetalMovement: 'Normal',
    followUp: 'ANC_RUTIN',
    nakesNotes: 'Pantau tekanan darah ketat.',
    nakesId: 'bidan',
    status: 'COMPLETED'
  },
  // KUNJUNGAN PASIEN MANGKIR 2 (SARI - MANGKIR SEJAK AWAL FEB)
  {
    id: 'v-sari-1',
    patientId: 'ANC-2025-1007',
    visitDate: '2026-01-10',
    scheduledDate: '2026-01-10',
    nextVisitDate: '2026-02-10', // SUDAH LEWAT
    weight: 60.5,
    bloodPressure: '120/80',
    tfu: 12,
    djj: 140,
    hb: 10.2,
    complaints: 'Lemas',
    dangerSigns: [],
    edema: false,
    fetalMovement: 'Normal',
    followUp: 'ANC_RUTIN',
    nakesNotes: 'TTD ditingkatkan.',
    nakesId: 'bidan',
    status: 'COMPLETED'
  }
];

export const EDUCATION_LIST: EducationContent[] = [
  {
    id: 'e1',
    title: 'Gizi Seimbang Ibu Hamil (Kemenkes)',
    type: 'TEXT',
    category: 'Gizi',
    content: 'Pentingnya asupan protein, zat besi, dan asam folat selama masa kehamilan untuk mencegah anemia dan stunting.',
    thumbnail: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=800&q=80',
    url: 'https://ayosehat.kemkes.go.id/pentingnya-pemenuhan-gizi-seimbang-bagi-ibu-hamil'
  },
  {
    id: 'e2',
    title: 'Tanda Bahaya Kehamilan (Video)',
    type: 'VIDEO',
    category: 'Emergensi',
    content: 'Visualisasi gejala kritis seperti perdarahan, pusing hebat, dan bengkak pada kaki yang perlu segera ditangani.',
    thumbnail: 'https://images.unsplash.com/photo-1505751172107-597d5a4d73dd?auto=format&fit=crop&w=800&q=80',
    url: 'https://www.youtube.com/watch?v=kYI0W7U2H_Y'
  },
  {
    id: 'e3',
    title: 'Tips Persalinan Aman & Nyaman',
    type: 'TEXT',
    category: 'Persiapan',
    content: 'Persiapan fisik dan mental menjelang persalinan, termasuk teknik pernapasan dan perlengkapan tas rumah sakit.',
    thumbnail: 'https://images.unsplash.com/photo-1519494080410-f9aa76cb4283?auto=format&fit=crop&w=800&q=80',
    url: 'https://promkes.kemkes.go.id/6-persiapan-persalinan-yang-harus-diketahui-ibu-hamil'
  },
  {
    id: 'e4',
    title: 'Pentingnya Tablet Tambah Darah',
    type: 'TEXT',
    category: 'Gizi',
    content: 'Alasan mengapa ibu hamil wajib mengonsumsi TTD minimal 90 tablet selama masa kehamilan.',
    thumbnail: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
    url: 'https://sehatnegeriku.kemkes.go.id/baca/rilis-media/20230125/4742278/cegah-stunting-sejak-hamil-dengan-konsumsi-tablet-tambah-darah/'
  }
];
